import { audit_json } from './engine.js';
const $ = id => document.getElementById(id);
const labels = {ROLE_POLICY_VIOLATION:['角色监督范围错误','该 token 属于当前策略排除的角色，却仍参与监督。'],PADDING_SUPERVISED:['Padding 参与监督','注意力标记为 0 的 token 带有训练标签。'],LABEL_TOKEN_MISMATCH:['训练标签与 token 不一致','此契约要求 label 与同位置 token 一致，或设为 -100。'],NO_SUPERVISION:['整条样本没有监督信号','所有训练标签均为 -100，请确认是否为有意设置。'],SUPERVISION_REDUCED:['监督信号减少','当前监督数量少于提供的基线，需检查截断或预处理。'],SOURCE_OVERLAP:['样本来源区间重叠','同一个 token 被多个来源区间覆盖。'],ROLE_OVERLAP:['对话角色区间重叠','同一个 token 被多个角色区间覆盖。'],ROLE_PROVENANCE_MISSING:['角色证据不足','缺少完整的角色映射，相关策略无法得到完整验证。'],SOURCE_PROVENANCE_MISSING:['来源证据不足','缺少来源区间，无法完整核对样本拼接。'],PACKING_CROSS_SOURCE_TARGET:['跨样本预测目标','后续来源的第一个 token 没有被忽略，普通因果注意力会从上一来源预测它。'],FIRST_TOKEN_NOT_PREDICTED:['首个标签不产生预测','模型内部位移时，位置 0 的标签不会参与下一 token 预测。']};
const severityName={error:'错误',warning:'提示',unknown:'缺少证据'};
const roleName={user:'用户',assistant:'助手',system:'系统',tool:'工具',unknown:'未知角色',conflict:'角色冲突'};
const stateName={supervised:'参与监督',ignored:'已忽略',padding:'Padding',error:'发现问题',unknown:'无法判断'};
let result, input, currentSample=0;
function element(tag, cls, text){const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node;}
function run(){try{input=JSON.parse($('input').value);result=JSON.parse(audit_json($('input').value));if(!result.ok)throw new Error(result.error);$('notice').textContent='';currentSample=0;render();}catch(e){result=null;$('notice').textContent='无法审计：'+e.message;$('metrics').replaceChildren();$('tokens').replaceChildren();$('findings').replaceChildren();$('role-track').replaceChildren();$('sample').replaceChildren();$('detail').textContent='请修正输入数据后重新运行。';$('ratio').textContent='—';$('progress').style.width='0%';}}
function render(){const report=result.report;const cards=[['审计结果',({pass:'通过',review:'需复核',fail:'发现错误'})[report.status],'仅针对当前声明的契约'],['检查 token',report.token_count,report.sample_count+' 条样本'],['监督标签',report.supervised_tokens,'label 不为 -100 的位置'],['发现的问题',report.error_count+report.warning_count+report.unknown_count,report.error_count+' 错误 · '+report.warning_count+' 提示 · '+report.unknown_count+' 待核实']];$('metrics').replaceChildren(...cards.map(([title,value,sub],i)=>{const node=element('div','metric'+((i===0&&report.status!=='pass')||i===3&&report.error_count?' alert':''));node.append(element('small','',title),element('strong','',String(value)),element('p','',sub));return node;}));$('sample').replaceChildren(...report.samples.map((s,i)=>{const o=element('option','',s.id);o.value=i;return o;}));renderSample();renderFindings();}
function renderSample(){const s=result.report.samples[currentSample];$('tokens').replaceChildren();$('role-track').replaceChildren();if(!s)return;let prior,groups=[];for(const role of s.roles){if(role!==prior){groups.push({role,count:1});prior=role;}else groups.at(-1).count++;}for(const group of groups){const node=element('div','role-group '+group.role,(roleName[group.role]||group.role)+' · '+group.count);node.style.flex=group.count;$('role-track').append(node);}for(let i=0;i<s.tokens;i++){const token=element('button','token '+s.states[i],String(input.samples.find(x=>x.id===s.id)?.input_ids[i]??'?'));token.append(element('span','','#'+i));token.setAttribute('aria-label','token '+i+' '+stateName[s.states[i]]);token.onclick=()=>inspect(i);$('tokens').append(token);}$('ratio').textContent=(s.supervised_ratio*100).toFixed(1)+'%';$('progress').style.width=(s.supervised_ratio*100)+'%';$('detail').textContent='点击一个 token，查看标签、角色与来源证据。';}
function inspect(index){const s=result.report.samples[currentSample];const data=input.samples.find(x=>x.id===s.id);[...$('tokens').children].forEach((node,i)=>node.classList.toggle('selected',i===index));$('detail').textContent=`位置 #${index} · Token ${data?.input_ids[index]} · Label ${data?.labels[index]??'缺失'} · Attention ${data?.attention_mask[index]??'缺失'} · ${roleName[s.roles[index]]||s.roles[index]} · ${stateName[s.states[index]]} · 来源 ${s.source_ids[index]}`;}
function renderFindings(){if(!result)return;const selected=$('filter').value;const findings=result.report.findings.filter(f=>selected==='all'||f.severity===selected);$('findings').replaceChildren();if(!findings.length){const empty=element('div','clean-state');empty.append(element('span','','✓'),element('div','',selected==='all'?'没有发现契约问题':'此分类没有问题'));$('findings').append(empty);return;}for(const f of findings){const node=element('article','finding');const top=element('div','finding-top');top.append(element('b','',labels[f.code]?.[0]||f.code),element('span','severity '+(f.severity==='error'?'error':f.severity==='warning'?'unknown':'ignored'),severityName[f.severity]));node.append(top,element('p','',labels[f.code]?.[1]||f.message));const button=element('button','',(f.sample_id||'数据集')+(f.token_index!=null?' / token #'+f.token_index:''));button.onclick=()=>{const i=result.report.samples.findIndex(s=>s.id===f.sample_id);if(i>=0){currentSample=i;$('sample').value=i;renderSample();if(f.token_index!=null)inspect(f.token_index);$('tokens').scrollIntoView({block:'nearest',behavior:'smooth'});}};node.append(button);$('findings').append(node);}}
async function preset(){try{const response=await fetch('./examples/'+$('preset').value+'.json');if(!response.ok)throw new Error('示例加载失败');$('input').value=JSON.stringify(await response.json(),null,2);run();}catch(e){$('notice').textContent=e.message;}}
$('run').onclick=run;$('preset').onchange=preset;$('sample').onchange=()=>{currentSample=Number($('sample').value);renderSample();};$('filter').onchange=renderFindings;
$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;if(file.size>1048576){$('notice').textContent='首版支持最大 1 MiB 的 JSON 文件。';return;}$('input').value=await file.text();run();};
$('export').onclick=()=>{if(!result){$('notice').textContent='请先成功运行审计。';return;}const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='supervision-audit-report.json';a.click();URL.revokeObjectURL(url);};
await preset();
